Node fs writefile
OSAdams/m2-0522-code-solutions pull request #22
Opened 2022-06-25 16:10 UTC by OSAdams

![image](https://user-images.githubusercontent.com/76730244/175781824-09d4d162-2fe6-48bc-9977-58c16e90087f.png)

2022-06-25 16:15 UTC, OSAdams commented
![image](https://user-images.githubusercontent.com/76730244/175782021-f606d364-9361-4d3d-a51b-3526658946f8.png)

2022-06-28 00:56 UTC, TimelikeClosure requested changes

2022-06-28 00:56 UTC, TimelikeClosure commented on node-fs-writefile/write-rand.js
> +fs.writeFile('random.txt', `${Math.random().toString()} \n`, 'utf8', err => {
You don't need to manually call `.toString()` if something is passed to a template literal, it will automatically convert it.

2022-06-28 00:56 UTC, TimelikeClosure commented on node-fs-writefile/cp.js
> +  fs.writeFile(process.argv[3], `${data}\n`, 'utf8', err => {
`cp.js` should produce an exact copy, without adding any characters.

2022-06-28 02:11 UTC, OSAdams commented
![image](https://user-images.githubusercontent.com/76730244/176076323-b078f903-7fdd-4b30-98b4-6936e1d3ac52.png)

2022-06-28 02:14 UTC, TimelikeClosure approved these changes

2022-06-28 02:14 UTC, merged