Express post json
OSAdams/m2-0522-code-solutions pull request #31
Opened 2022-07-08 01:52 UTC by OSAdams

![express-post-json](https://user-images.githubusercontent.com/76730244/177900625-c3aa8948-483b-4f91-9b95-724a6d44fbb6.gif)

2022-07-08 02:09 UTC, TimelikeClosure requested changes

2022-07-08 02:09 UTC, TimelikeClosure commented on express-post-json/index.js
> +});
Make sure your middleware sends exactly one response per request.

2022-07-12 01:51 UTC, OSAdams commented
![image](https://user-images.githubusercontent.com/76730244/178391245-9b00aeca-eccf-4da6-aa9b-654bc6807b2f.png)

2022-07-12 01:53 UTC, TimelikeClosure requested changes

2022-07-12 01:53 UTC, TimelikeClosure commented on express-post-json/index.js
> +});
Make sure you're sending exactly one response pre-request.

2022-07-12 02:13 UTC, OSAdams commented
![image](https://user-images.githubusercontent.com/76730244/178393798-0d00fb9f-6e3d-426c-b8e6-3d768fbbd63d.png)

2022-07-12 02:14 UTC, TimelikeClosure approved these changes

2022-07-12 02:15 UTC, merged