Express notes api
OSAdams/m2-0522-code-solutions pull request #32
Opened 2022-07-13 05:22 UTC by OSAdams

`/workspaces/m2-0522-code-solutions/express-notes-api (express-notes-api) λ http -v get localhost:3000/api/notes
GET /api/notes HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:3000
User-Agent: HTTPie/1.0.3

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 87
Content-Type: application/json; charset=utf-8
Date: Wed, 13 Jul 2022 05:14:30 GMT
ETag: W/"57-7LcEsN2adzUrcMtQzhdJVq26vUo"
Keep-Alive: timeout=5
X-Powered-By: Express

[
    {
        "content": "Totally tubular two",
        "id": 13
    },
    {
        "content": "Totally tubular tjree",
        "id": 14
    }
]

/workspaces/m2-0522-code-solutions/express-notes-api (express-notes-api) λ http -v delete localhost:3000/api/notes/13
DELETE /api/notes/13 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Host: localhost:3000
User-Agent: HTTPie/1.0.3

HTTP/1.1 204 No Content
Connection: keep-alive
Date: Wed, 13 Jul 2022 05:14:36 GMT
ETag: W/"a-bAsFyilMr4Ra1hIU5PyoyFRunpI"
Keep-Alive: timeout=5
X-Powered-By: Express

/workspaces/m2-0522-code-solutions/express-notes-api (express-notes-api) λ http -v get localhost:3000/api/notes
GET /api/notes HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:3000
User-Agent: HTTPie/1.0.3

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 45
Content-Type: application/json; charset=utf-8
Date: Wed, 13 Jul 2022 05:15:04 GMT
ETag: W/"2d-8//YmNVvlB9aCFyPeq70VdHcE8o"
Keep-Alive: timeout=5
X-Powered-By: Express

[
    {
        "content": "Totally tubular tjree",
        "id": 14
    }
]

/workspaces/m2-0522-code-solutions/express-notes-api (express-notes-api) λ http -v put localhost:3000/api/notes/14 content="update test"
PUT /api/notes/14 HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 26
Content-Type: application/json
Host: localhost:3000
User-Agent: HTTPie/1.0.3

{
    "content": "update test"
}

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 2
Content-Type: text/plain; charset=utf-8
Date: Wed, 13 Jul 2022 05:15:28 GMT
ETag: W/"2-nOO9QiTIwXgNtWtBJezz8kv3SLc"
Keep-Alive: timeout=5
X-Powered-By: Express

OK

/workspaces/m2-0522-code-solutions/express-notes-api (express-notes-api) λ http -v get localhost:3000/api/notes
GET /api/notes HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:3000
User-Agent: HTTPie/1.0.3

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 35
Content-Type: application/json; charset=utf-8
Date: Wed, 13 Jul 2022 05:15:33 GMT
ETag: W/"23-JuxyqxPfWvtauD6bFHKTagdmUOs"
Keep-Alive: timeout=5
X-Powered-By: Express

[
    {
        "content": "update test",
        "id": 14
    }
]

/workspaces/m2-0522-code-solutions/express-notes-api (express-notes-api) λ http -v get localhost:3000/api/notes/14
GET /api/notes/14 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:3000
User-Agent: HTTPie/1.0.3

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 33
Content-Type: application/json; charset=utf-8
Date: Wed, 13 Jul 2022 05:15:55 GMT
ETag: W/"21-wQpGoPw84DakCLrahv0qCMCwUGI"
Keep-Alive: timeout=5
X-Powered-By: Express

{
    "content": "update test",
    "id": 14
}
`

2022-07-14 00:32 UTC, TimelikeClosure requested changes

2022-07-14 00:32 UTC, TimelikeClosure commented on express-notes-api/index.js
> +    res.status(400).json(error);
An `id` of `0` should also result in a `400 Bad Request`.

2022-07-14 00:32 UTC, TimelikeClosure commented on express-notes-api/index.js
> +        res.sendStatus(200);
Note updates should include the note's new info in the response:

---

![image](https://user-images.githubusercontent.com/16143771/178859666-434f7790-3b43-4d23-9793-e93655936048.png)

2022-07-15 01:58 UTC, OSAdams commented
![image](https://user-images.githubusercontent.com/76730244/179131518-f0bb4dfe-7249-45b2-80fd-db2a23fe2a89.png)

2022-07-15 02:00 UTC, thebearingedge requested changes

2022-07-15 02:00 UTC, thebearingedge commented on express-notes-api/index.js
> +    res.status(400).json(error);
If you change this to `<= 0`, it will catch zero id submissions too.

2022-07-15 02:00 UTC, thebearingedge commented on express-notes-api/index.js
> +      if (err) {
In all of your `writeFile` callbacks, be sure to `console.error(err)` so that you can debug your server if something goes wrong.

2022-07-15 02:07 UTC, thebearingedge approved these changes

2022-07-15 02:17 UTC, merged