Sql aggregates
OSAdams/m2-0522-code-solutions pull request #40
Opened 2022-07-23 17:18 UTC by OSAdams

![image](https://user-images.githubusercontent.com/76730244/180615817-89d2f3b5-93d4-4f39-afd9-9f69c4c166f7.png)

2022-07-26 02:49 UTC, TimelikeClosure requested changes

2022-07-26 02:49 UTC, TimelikeClosure commented on sql-aggregates/starring-in.sql
> + GROUP BY name
Your query should find the right actor, regardless of which id they have:

---

![image](https://user-images.githubusercontent.com/16143771/180912458-a91e05f1-6fc3-433c-b805-6f4fe09c02ce.png)

2022-07-26 16:10 UTC, OSAdams commented
![image](https://user-images.githubusercontent.com/76730244/181056810-453d3506-4310-47d4-a6fa-e8eab1c503e1.png)

2022-07-27 01:43 UTC, TimelikeClosure approved these changes

2022-08-01 17:20 UTC, merged